# Generated by Django 3.1.2 on 2021-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QeNoBiApp', '0003_remove_property_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdescription',
            name='customers_properties',
            field=models.ManyToManyField(blank=True, related_name='dataset_customers', to='QeNoBiApp.Property'),
        ),
        migrations.AlterField(
            model_name='datasetdescription',
            name='items_properties',
            field=models.ManyToManyField(blank=True, related_name='dataset_items', to='QeNoBiApp.Property'),
        ),
    ]
