# Generated by Django 3.1.2 on 2021-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QeNoBiApp', '0004_auto_20210302_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeGranularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
